services:
  bot-for-ytdlp:
    build:
      context: .
    restart: always
    environment:
      - TELEGRAM_BOT_KEY=
      - YOUTUBE_API_KEY=
    volumes:
      - ./configs:/app/configs
      - ./downloads:/app/downloads
      - ./logs:/app/logs